<?php
echo "<!DOCTYPE html>\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "    <meta charset=\"utf-8\">\n"; 
echo "    <title>Untitled - set my name - UXPin Preview</title>\n"; 
echo "    <meta content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0\" name=\"viewport\">\n"; 
echo "    <meta name=\"keywords\" content=\"\">\n"; 
echo "    <meta name=\"description\" content=\"\">\n"; 
echo "    <link rel=\"shortcut icon\" href=\"/img/favicon-90cb8314.ico\">\n"; 
echo "    <link rel=\"icon\" type=\"image/png\" href=\"/img/favicon-90cb8314.ico\">\n"; 
echo "    <link rel=\"icon\" href=\"/img/ios-logo-180x180-4f260175.png\">\n"; 
echo "    <link rel=\"apple-touch-icon\" href=\"/img/ios-logo-180x180-4f260175.png\">\n"; 
echo "    <meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,minimal-ui\">\n"; 
echo "    <meta name=\"mobile-web-app-capable\" content=\"yes\">\n"; 
echo "    <meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\n"; 
echo "    <meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black-translucent\">\n"; 
echo "    <base href=\"//collaborate.uxpin.com/07d88a4b6de8b06e53b6a5f924077f64e0f1b6b5\">\n"; 
echo "    <link rel=\"stylesheet\" href=\"//collaborate.uxpincdn.com/styles/Preview-d842793d.css\">\n"; 
echo "    <link rel=\"chrome-webstore-item\" href=\"https://chrome.google.com/webstore/detail/bgibmbhbcdfckbcbdkihlclfildbaehc\">\n"; 
echo "</head>\n"; 
echo "<body ng-controller=\"HomeController\" class=\"loading\" ng-class=\"{'loading' : isLoading, 'left-panel-active' : (isVisible && sidebarVisible), 'sitemap-visible' : (sitemapVisible && sidebarVisible), 'panel-visible' : (panelVisible && sidebarVisible), 'adding-comment' : isAddingComment, 'dragging' : dragging, 'no-toolbar' : noToolbar || isParticipant, 'crosshair-cursor' : showCrosshairCursor, 'sidebar-collapsed' : sidebarVisible === false}\" ng-keydown=\"keyDown($event)\">\n"; 
echo "        <script>\n"; 
echo "    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\n"; 
echo "        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n"; 
echo "        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n"; 
echo "    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');\n"; 
echo "\n"; 
echo "    ga('create', 'UA-19584088-9', 'auto');\n"; 
echo "</script>\n"; 
echo "        <script type=\"text/javascript\">\n"; 
echo "    var _kmq = _kmq || [];\n"; 
echo "    var _kmk = _kmk || '68f9313d866df031326598d49a29feb2a560246d';\n"; 
echo "    function _kms(u){\n"; 
echo "        setTimeout(function(){\n"; 
echo "            var d = document, f = d.getElementsByTagName('script')[0],\n"; 
echo "                s = d.createElement('script');\n"; 
echo "            s.type = 'text/javascript'; s.async = true; s.src = u;\n"; 
echo "            f.parentNode.insertBefore(s, f);\n"; 
echo "        }, 1);\n"; 
echo "    }\n"; 
echo "    _kms('//i.kissmetrics.com/i.js');\n"; 
echo "    _kms('//doug1izaerwt3.cloudfront.net/' + _kmk + '.1.js');\n"; 
echo "</script>\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "(function(){var w=window;var ic=w.Intercom;if(typeof ic===\"function\"){ic('reattach_activator');ic('update',intercomSettings);}else{var d=document;var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};w.Intercom=i;function l(){var s=d.createElement('script');s.type='text/javascript';s.async=true;\n"; 
echo "s.src='https://widget.intercom.io/widget/{app_id}';\n"; 
echo "var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);}if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})()\n"; 
echo "</script>\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "  (function(a, ns, cb, l) {\n"; 
echo "      l = document.createElement('link');\n"; 
echo "      l.rel = \"stylesheet\"\n"; 
echo "      l.type = \"text/css\"\n"; 
echo "      l.href = \"//fast.appcues.com/appcues.css\"\n"; 
echo "      l.id = 'appcues-css'\n"; 
echo "      document.getElementsByTagName('head')[0].appendChild(l);\n"; 
echo "      window[ns] = function(callback) {\n"; 
echo "        (window[ns].q = window[ns].q || []).push(callback);\n"; 
echo "        if (window[a] != null) {\n"; 
echo "          while (window[ns].q.length) {\n"; 
echo "            cb = window[ns].q.shift();\n"; 
echo "            if (typeof cb === 'function') cb();\n"; 
echo "          }\n"; 
echo "        }\n"; 
echo "      };\n"; 
echo "    })('Appcues', 'AppcuesReady');\n"; 
echo "</script>\n"; 
echo "<script src=\"//fast.appcues.com/14532.js\" async defer onload=\"AppcuesReady()\"></script>\n"; 
echo "    <section\n"; 
echo "        ng-if=\"canShowLoginToolbar\"\n"; 
echo "        ng-controller=\"LoginToolbarController\"\n"; 
echo "        class=\"login-toolbar top-position with-input set-name\"\n"; 
echo "        ng-class=\"{'visible' : showLoginToolbar, 'show-form' : showNameForm, 'success' : nameSet}\"\n"; 
echo "        ng-click=\"clickStopPropagation($event)\">\n"; 
echo "        <p>Hey there, stranger! <a ng-href=\"\" ng-click=\"onClickShowNameForm($event);\">Set your name</a> to introduce yourself to the team. Already have an account? <a ng-mouseover=\"updateReferer()\" ng-href=\"{{referer}}\">Log in</a>.</p>\n"; 
echo "        <form>\n"; 
echo "            <fieldset>\n"; 
echo "                <p>My name is <input type=\"text\" ng-model=\"anonymousName\" sync-focus-with=\"focused\" ng-blur=\"setFocus(false);\" ng-keydown=\"onKeyDown($event)\" ng-change=\"onChange()\"><button class=\"btn-flat white-style\" ng-disabled=\"disabled\" ng-click=\"onClickSetName($event)\">That's me</button></p>\n"; 
echo "            </fieldset>\n"; 
echo "        </form>\n"; 
echo "    </section>\n"; 
echo "    <div ui-view></div>\n"; 
echo "    <div ng-class=\"{'fade-in' : panelFadeIn}\" ui-view=\"comments\"></div>\n"; 
echo "    <div ng-class=\"{'fade-in' : sitemapFadeIn}\" ui-view=\"sitemap\"></div>\n"; 
echo "    <div ui-view=\"nav\"></div>\n"; 
echo "    <div ui-view=\"canvas\"></div>\n"; 
echo "    <section id=\"responsive-toolbar\" adjust-to-viewport-size>\n"; 
echo "        <a class=\"only-icon-font icon-font-arrow show-main-toolbar\" ng-click=\"showToolbar()\" toggle-visibility toggle-flag=\"!isToolbarVisible()\" toggle-width-open=\"34\" toggle-width-closed=\"0\" ng-if=\"!params.isDocument\">\n"; 
echo "            Show main toolbar\n"; 
echo "            <span class=\"tooltip blue-style bottom-arrow\">Show main toolbar</span>\n"; 
echo "        </a>\n"; 
echo "        <ul ui-view=\"breakpoints\" ng-if=\"breakpointsVisible\"></ul>\n"; 
echo "        <ul ui-view=\"breadcrumbs\" ng-if=\"breadcrumbsVisible\" class=\"breadcrumbs\"></ul>\n"; 
echo "        <div ui-view=\"settings\"></div>\n"; 
echo "    </section>\n"; 
echo "    <div ui-view=\"overlay\"></div>\n"; 
echo "    <div class=\"loader\"></div>\n"; 
echo "    <script type=\"text/javascript\">\n"; 
echo "    window.ApplicationConfiguration = {\n"; 
echo "            rollbar:{\"postServerAccessToken\":\"41207a8115a54d37abe5ffacd0c7e4a4\",\"postClientAccessToken\":\"49dfce4d74984afea0b7e5261c5d6237\",\"options\":{\"exceptions\":{\"environment\":\"production\"},\"reporter\":{\"verbose\":true,\"environment\":\"production\",\"root\":\"/var/www/uxpin-preview/releases/20160520133303/config/env\"}}},\n"; 
echo "            socketServerURL: 'https://pubsub.uxpin.com',\n"; 
echo "            voicechatServerURL: '//voicechat.uxpin.com',\n"; 
echo "            loginPageURL: 'https://app.uxpin.com',\n"; 
echo "            upgradePlanURL: 'https://app.uxpin.com/dms/Dashboard/Default?show_action=ba',\n"; 
echo "            cookieDomain: '.uxpin.com',\n"; 
echo "            userData:{\"id_user\":\"574295\",\"name\":\"amkamal@oakland.edu\",\"email\":\"amkamal@oakland.edu\",\"avatar\":\"https://s.gravatar.com/avatar/3c9e67a6276a8161aaa7ee98b404d6dd?s=30\",\"timezone\":\"America/Denver\",\"is_trial\":true,\"is_anonymous\":false,\"id_session\":\"js8oeoopkg3u7nqssefoj06rpnk9bg6736jtu0bpg01outsr3el0\",\"is_owner\":true,\"hash\":\"15d85bd7fed0f641365a34761b418f55b49b4850e8a6f7411392b70d67ac7e41\"},\n"; 
echo "            project:{\"id_project\":5569676,\"id_collection\":1256592,\"name\":\"Untitled - set my name\",\"hash\":\"07d88a4b6de8b06e53b6a5f924077f64e0f1b6b5\",\"type\":\"W\",\"features\":{\"live_share\":true,\"user_testing\":true,\"password\":true,\"new_editor\":false,\"new_engine\":true,\"ignore_engine_version\":false},\"created_at\":\"2016-05-22T00:01:37+01:00\",\"updated_at\":\"2016-05-22T00:05:01+01:00\"},\n"; 
echo "            uxpinURL: 'https://redesigned.uxpin.com/',\n"; 
echo "            userContentPrefix: 's3.amazonaws.com/upload.uxpin',\n"; 
echo "            userContentPrefixCached: 'uc.uxpin.com',\n"; 
echo "            staticContentPrefixCached: 'https://static.uxpincdn.com',\n"; 
echo "        })\n"; 
echo "        if (window.ApplicationConfiguration.userData.is_anonymous === false) {\n"; 
echo "            if (typeof Intercom === 'function')  {\n"; 
echo "                Intercom('boot', {\n"; 
echo "                    user_hash: '15d85bd7fed0f641365a34761b418f55b49b4850e8a6f7411392b70d67ac7e41',\n"; 
echo "                    user_id: '574295',\n"; 
echo "                    email: 'amkamal@oakland.edu',\n"; 
echo "                    app_id: 'c5ea3ec6243c3a8164fb702a95a3e61ca193a2cc'\n"; 
echo "                });\n"; 
echo "                Intercom('trackEvent', 'Opened preview');\n"; 
echo "            }\n"; 
echo "            if (typeof AppcuesReady === 'function') {\n"; 
echo "                AppcuesReady(function() {\n"; 
echo "                    Appcues.identify('574295', {\n"; 
echo "                        email: 'amkamal@oakland.edu',\n"; 
echo "                    });\n"; 
echo "                });\n"; 
echo "            }\n"; 
echo "        }\n"; 
echo "    </script>\n"; 
echo "        <script type=\"text/javascript\" src=\"//cdn.socket.io/socket.io-1.3.7.js\"></script>\n"; 
echo "        <script type=\"text/javascript\" src=\"//live.uxpincdn.com/plivo/plivo.min.js\"></script>\n"; 
echo "        <script type=\"text/javascript\" src=\"//static.opentok.com/v2/js/opentok.min.js\"></script>\n"; 
echo "        <script type=\"text/javascript\" src=\"//collaborate.uxpincdn.com/scripts/engine-454bf804.js\"></script>\n"; 
echo "        <script type=\"text/javascript\" src=\"//collaborate.uxpincdn.com/scripts/vendors-83b108c8.js\"></script>\n"; 
echo "        <script type=\"text/javascript\" src=\"//collaborate.uxpincdn.com/scripts/app-ae4bd499.js\"></script>\n"; 
echo "    <app-view-promo ng-if=\"isAppViewAvailable\"></app-view-promo>\n"; 
echo "</body>\n"; 
echo "</html>\n";
?>
