<?php
echo "<!DOCTYPE html>\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\"/>\n"; 
echo "             \n"; 
echo "    \n"; 
echo "                <meta charset=\"utf-8\"/>\n"; 
echo "<title>mysite</title>\n"; 
echo "<meta name=\"fb_admins_meta_tag\" content=\"\"/>\n"; 
echo "<link rel=\"shortcut icon\" href=\"http://www.wix.com/favicon.ico\" type=\"image/x-icon\"/>\n"; 
echo "<link rel=\"apple-touch-icon\" href=\"http://www.wix.com/favicon.ico\" type=\"image/x-icon\"/>\n"; 
echo "    <meta http-equiv=\"X-Wix-Renderer-Server\" content=\"app16.tam\"/>\n"; 
echo "<meta http-equiv=\"X-Wix-Meta-Site-Id\" content=\"e8ede0b8-7ec6-4ec4-9fad-a7be0367eea0\"/>\n"; 
echo "<meta http-equiv=\"X-Wix-Application-Instance-Id\" content=\"8c4f98c5-2560-4929-8aac-a91d70f27b69\"/>\n"; 
echo "<meta http-equiv=\"X-Wix-Published-Version\" content=\"3\"/>\n"; 
echo "\n"; 
echo "<meta http-equiv=\"etag\" content=\"6cf66230a5da9e4681583ccae34e25f5\"/>\n"; 
echo "<meta property=\"og:title\" content=\"mysite\"/>\n"; 
echo "<meta property=\"og:type\" content=\"article\"/>\n"; 
echo "<meta property=\"og:url\" content=\"http://amkamal4.wix.com/mysite\"/>\n"; 
echo "<meta property=\"og:site_name\" content=\"mysite\"/>\n"; 
echo "<meta name=\"SKYPE_TOOLBAR\" content=\"SKYPE_TOOLBAR_PARSER_COMPATIBLE\"/>\n"; 
echo "\n"; 
echo "<meta id=\"wixMobileViewport\" name=\"viewport\" content=\"minimum-scale=0.25, maximum-scale=1.2\"/>\n"; 
echo "\n"; 
echo "\n"; 
echo "        \n"; 
echo "\n"; 
echo "    <script>\n"; 
echo "    // BEAT MESSAGE\n"; 
echo "    try {\n"; 
echo "        window.wixBiSession = {\n"; 
echo "            initialTimestamp : Date.now(),\n"; 
echo "            viewerSessionId: 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c)\n"; 
echo "                    { var r = Math.random()*16|0, v = c == 'x' ? r : (r&0x3|0x8); return v.toString(16); }\n"; 
echo "            )\n"; 
echo "        };\n"; 
echo "        (new Image()).src = 'http://frog.wix.com/bt?src=29&evid=3&pn=1&et=1&v=1.1392.12&vsi=' + wixBiSession.viewerSessionId +\n"; 
echo "                '&url=' + encodeURIComponent(location.href.replace(/^http(s)?:\/\/(www\.)?/, '')) +\n"; 
echo "                '&isp=0&st=2&ts=0&c=' + wixBiSession.initialTimestamp;\n"; 
echo "    } catch (e){}\n"; 
echo "    // BEAT MESSAGE END\n"; 
echo "</script>\n"; 
echo "\n"; 
echo "    \n"; 
echo "\n"; 
echo "    <!-- META DATA -->\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "\n"; 
echo "    var serviceTopology = {\"serverName\":\"app16.tam\",\"cacheKillerVersion\":\"1\",\"staticServerUrl\":\"http://static.parastorage.com/\",\"usersScriptsRoot\":\"http://static.parastorage.com/services/wix-users/2.613.0\",\"biServerUrl\":\"http://frog.wix.com/\",\"userServerUrl\":\"http://users.wix.com/\",\"billingServerUrl\":\"http://premium.wix.com/\",\"mediaRootUrl\":\"http://static.wixstatic.com/\",\"logServerUrl\":\"http://frog.wix.com/plebs\",\"monitoringServerUrl\":\"http://TODO/\",\"usersClientApiUrl\":\"https://users.wix.com/wix-users\",\"publicStaticBaseUri\":\"http://static.parastorage.com/services/wix-public/1.190.0\",\"basePublicUrl\":\"http://www.wix.com/\",\"postLoginUrl\":\"http://www.wix.com/my-account\",\"postSignUpUrl\":\"http://www.wix.com/new/account\",\"baseDomain\":\"wix.com\",\"staticMediaUrl\":\"https://static.wixstatic.com/media\",\"staticAudioUrl\":\"https://media.wix.com/mp3\",\"emailServer\":\"http://assets.wix.com/common-services/notification/invoke\",\"blobUrl\":\"https://static.parastorage.com/wix_blob\",\"htmlEditorUrl\":\"http://editor.wix.com/html\",\"siteMembersUrl\":\"https://users.wix.com/wix-sm\",\"scriptsLocationMap\":{\"wixapps\":\"https://static.parastorage.com/services/wixapps/2.484.0\",\"tpa\":\"https://static.parastorage.com/services/tpa/2.1062.0\",\"santa-resources\":\"https://static.parastorage.com/services/santa-resources/1.2.0\",\"wix-code-sdk\":\"https://static.parastorage.com/services/js-wixcode-sdk/1.15.0\",\"bootstrap\":\"https://static.parastorage.com/services/bootstrap/2.1229.49\",\"ck-editor\":\"https://static.parastorage.com/services/ck-editor/1.87.3\",\"it\":\"https://static.parastorage.com/services/experiments/it/1.37.0\",\"santa\":\"https://static.parastorage.com/services/santa/1.1392.12\",\"skins\":\"https://static.parastorage.com/services/skins/2.1229.49\",\"core\":\"https://static.parastorage.com/services/core/2.1229.49\",\"sitemembers\":\"https://static.parastorage.com/services/sm-js-sdk/1.31.0\",\"automation\":\"https://static.parastorage.com/services/automation/1.23.0\",\"web\":\"https://static.parastorage.com/services/web/2.1229.49\",\"ecommerce\":\"https://static.parastorage.com/services/ecommerce/1.203.0\",\"hotfixes\":\"https://static.parastorage.com/services/experiments/hotfixes/1.15.0\",\"langs\":\"https://static.parastorage.com/services/langs/2.568.0\",\"santa-versions\":\"https://static.parastorage.com/services/santa-versions/1.419.0\",\"ut\":\"https://static.parastorage.com/services/experiments/ut/1.2.0\"},\"developerMode\":false,\"productionMode\":true,\"staticServerFallbackUrl\":\"https://sslstatic.wix.com/\",\"staticVideoUrl\":\"http://video.wixstatic.com/\",\"scriptsDomainUrl\":\"https://static.parastorage.com/\",\"userFilesUrl\":\"http://static.parastorage.com/\",\"staticHTMLComponentUrl\":\"http://amkamal4.wix.com.usrfiles.com/\",\"secured\":false,\"ecommerceCheckoutUrl\":\"https://www.safer-checkout.com/\",\"premiumServerUrl\":\"https://premium.wix.com/\",\"appRepoUrl\":\"http://assets.wix.com/wix-lists-ds-webapp\",\"digitalGoodsServerUrl\":\"http://dgs.wixapps.net/\",\"wixCloudBaseDomain\":\"wix-code.com\",\"mailServiceSuffix\":\"/_api/common-services/notification/invoke\",\"staticVideoHeadRequestUrl\":\"http://storage.googleapis.com/video.wixstatic.com\",\"protectedPageResolverUrl\":\"https://site-pages.wix.com/_api/wix-public-html-info-webapp/resolve_protected_page_urls\",\"publicStaticsUrl\":\"http://static.parastorage.com/services/wix-public/1.190.0\",\"staticDocsUrl\":\"http://media.wix.com/ugd\"};\n"; 
echo "    var santaModels = true;\n"; 
echo "    var rendererModel = {\"metaSiteId\":\"e8ede0b8-7ec6-4ec4-9fad-a7be0367eea0\",\"siteInfo\":{\"documentType\":\"UGC\",\"applicationType\":\"HtmlWeb\",\"siteId\":\"8c4f98c5-2560-4929-8aac-a91d70f27b69\",\"siteTitleSEO\":\"mysite\"},\"clientSpecMap\":{\"2\":{\"type\":\"sitemembers\",\"applicationId\":2,\"collectionType\":\"Open\",\"smtoken\":\"bce6d27160e564554ded790b287b087017dd64386bfdfc890c5dada85f36bd1737cb08c576da2ebe26205cff5d1d9cd1a27768b028d8807bed7e0d93363ee58646bc3af91e0d4ae91fbd846b9a2f13dea14067eba79c08d090812b2558cf36fd\",\"smcollectionId\":\"bb44f0a3-68a8-42b0-8514-d9b9b5f3ebd9\"},\"1\":{\"type\":\"appbuilder\",\"applicationId\":1,\"appDefinitionId\":\"3d590cbc-4907-4cc4-b0b1-ddf2c5edf297\",\"instanceId\":\"1450a09d-32c3-1d16-3af8-1f4294c2fce0\",\"state\":\"Initialized\"}},\"premiumFeatures\":[],\"geo\":\"USA\",\"languageCode\":\"en\",\"previewMode\":false,\"userId\":\"59cac5fa-55e6-4b54-8337-ca2069e7beae\",\"siteMetaData\":{\"preloader\":{\"enabled\":false},\"adaptiveMobileOn\":true,\"quickActions\":{\"socialLinks\":[],\"colorScheme\":\"dark\",\"configuration\":{\"quickActionsMenuEnabled\":false,\"navigationMenuEnabled\":true,\"phoneEnabled\":false,\"emailEnabled\":false,\"addressEnabled\":false,\"socialLinksEnabled\":false}},\"contactInfo\":{\"companyName\":\"\",\"phone\":\"\",\"fax\":\"\",\"email\":\"\",\"address\":\"\"}},\"runningExperiments\":{\"wixappsPerformanceMeasuring\":\"new\",\"sv_allowEditingGaps\":\"new\",\"anchorsMenuAutoColor\":\"new\",\"actionsBehaviors\":\"new\",\"sv_minPH\":\"new\",\"sv_exp171\":\"new\",\"compStateMixin\":\"new\",\"sv_blogCleanExcerptStyles\":\"new\",\"sv_blogPagination\":\"new\",\"deepLinking\":\"new\",\"sv_passwordPages\":\"new\",\"fixGsapRaf\":\"new\",\"highlightAnchorsInMenu\":\"new\",\"improvedImageZoom\":\"new\",\"videoVisibilityApiSupport\":\"new\",\"sv_blogCategories\":\"new\",\"sendContactFormEmailsViaPong\":\"old\",\"sv_removeLoginByGuid\":\"new\",\"sv_appFlows\":\"new\",\"mobileAppBannerOnMobile\":\"new\",\"sv_blogVideoThumbnail\":\"new\",\"sv_dontShowGalleryLink\":\"new\",\"sv_textCompFilter\":\"new\"},\"urlFormatModel\":{\"format\":\"hashBang\",\"forbiddenPageUriSEOs\":[\"app\",\"apps\",\"_api\",\"robots.txt\",\"sitemap.xml\",\"feed.xml\",\"sites\"],\"pageIdToResolvedUriSEO\":{}},\"passwordProtectedPages\":[],\"useSandboxInHTMLComp\":true};\n"; 
echo "    var publicModel = {\"domain\":\"wix.com\",\"externalBaseUrl\":\"http:\/\/amkamal4.wix.com\/mysite\",\"unicodeExternalBaseUrl\":\"http:\/\/amkamal4.wix.com\/mysite\",\"pageList\":{\"masterPage\":[\"https:\/\/static.wixstatic.com\/sites\/59cac5_eb1204c4bb95399fd1f51557cf650223_3.json.z?v=3\",\"https:\/\/staticorigin.wixstatic.com\/sites\/59cac5_eb1204c4bb95399fd1f51557cf650223_3.json.z?v=3\",\"https:\/\/fallback.wix.com\/wix-html-editor-pages-webapp\/page\/59cac5_eb1204c4bb95399fd1f51557cf650223_3.json\"],\"pages\":[{\"pageId\":\"c204q\",\"title\":\"HOME\",\"pageUriSEO\":\"home\",\"urls\":[\"https:\/\/static.wixstatic.com\/sites\/59cac5_3f2f3e1a2079313e42f4f9e070b8f496_3.json.z?v=3\",\"https:\/\/staticorigin.wixstatic.com\/sites\/59cac5_3f2f3e1a2079313e42f4f9e070b8f496_3.json.z?v=3\",\"https:\/\/fallback.wix.com\/wix-html-editor-pages-webapp\/page\/59cac5_3f2f3e1a2079313e42f4f9e070b8f496_3.json\"]}],\"mainPageId\":\"c204q\"},\"timeSincePublish\":6179,\"favicon\":\"\",\"deviceInfo\":{\"deviceType\":\"Desktop\",\"browserType\":\"Chrome\",\"browserVersion\":50},\"siteRevision\":3};\n"; 
echo "\n"; 
echo "\n"; 
echo "    var googleAnalytics = \"UA-2117194-61\"\n"; 
echo "    ;\n"; 
echo "\n"; 
echo "    var googleRemarketing = \"\";\n"; 
echo "    var facebookRemarketing = \"\";\n"; 
echo "    var yandexMetrika = \"\";\n"; 
echo "\n"; 
echo "</script>\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "            <meta name=\"fragment\" content=\"!\"/>\n"; 
echo "    \n"; 
echo "    <!-- DATA -->\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "    var adData = {\"topLabel\":\"<span class=\\"smallMusa\\">(Wix-Logo) </span>Create a <span class=\\"smallLogo\\">Wix</span> site!\",\"topContent\":\"100s of templates<br />No coding needed<br /><span class=\\"emphasis spacer\\">Start now >></span>\",\"footerLabel\":\"<div class=\\"adFootBox\\"><div class=\\"siteBanner\\" ><div class=\\"siteBanner\\"><div class=\\"wrapper\\"><div class=\\"bigMusa\\">(Wix Logo)</div><div class=\\"txt shd\\" style=\\"color:#fff\\">This site was created using </div> <div class=\\"txt shd\\"><a  href=\\"http://www.wix.com?utm_campaign=vir_wixad_live&experiment_id=abtestbanner122400001\\" style=\\"color:#fff\\"> WIX.com. </a></div> <div class=\\"txt shd\\" style=\\"color:#fff\\"> Create your own for FREE <span class=\\"emphasis\\"> >></span></div></div></div></div></div>\",\"adUrl\":\"http://www.wix.com/lpviral/enviral?utm_campaign=vir_wixad_live&experiment_id=abtestbanner122400001\"};\n"; 
echo "    var mobileAdData = {\"footerLabel\":\"7c3dbd_67131d7bd570478689be752141d4e28a.jpg\",\"adUrl\":\"http://www.wix.com?utm_campaign=vir_wixad_live&experiment_id=abtestbanner122400001\"};\n"; 
echo "    var usersDomain = \"https://users.wix.com/wix-users\";\n"; 
echo "        </script>\n"; 
echo "            <script type=\"text/javascript\">\n"; 
echo "    var santaBase = 'https://static.parastorage.com/services/santa/1.1392.12';\n"; 
echo "        var clientSideRender = true;\n"; 
echo "    </script>\n"; 
echo "<script src=\"https://static.parastorage.com/services/third-party/requirejs/2.1.15/require.min.js\"></script>\n"; 
echo "<script src=\"https://static.parastorage.com/services/santa/1.1392.12/app/main-r.min.js\"></script>\n"; 
echo "<link rel=\"stylesheet\" href=\"https://static.parastorage.com/services/santa/1.1392.12/static/css/viewer.css\">\n"; 
echo "\n"; 
echo "</head>\n"; 
echo "<body>\n"; 
echo "        <div id=\"SITE_CONTAINER\"></div>\n"; 
echo "\n"; 
echo "    \n"; 
echo "        \n"; 
echo "    \n"; 
echo "<div comp=\"wysiwyg.viewer.components.WixAds\" skin=\"wysiwyg.viewer.skins.wixadsskins.WixAdsWebSkin\" id=\"wixFooter\"></div>\n"; 
echo "    \n"; 
echo "    \n"; 
echo "        \n"; 
echo "    \n"; 
echo "\n"; 
echo "    </body>\n"; 
echo "</html>\n"; 
echo "\n";
?>
